config/routes.rb
Zmartcase::Application.routes.draw do

  get "email_accounts/index"

  get "email_accounts/edit"

  get "email_accounts/new"

  get "email_accounts/index"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  get "filter_mail/index"
  post "filter_mail/index"
  get "filter_mail/start_filtering"
  post "filter_mail/start_filtering"

  get "categories/uncategorized"
  post "categories/uncategorized"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  get "users/fetch"
  post "users/fetch"

  get "closed/:id" => "cases#closed_show", :as => "show_closed"

  resources :priorities
  resources :users
  get "dashboard" => "users#dashboard"
  resources :sessions
  resources :emails
  resources :email_accounts
  resources:notes
  resources :key_words
  resources :categories do
    resources :cases
  end

  root :to => 'users#dashboard'

end

app/models/case.rb
class Case < ActiveRecord::Base
  attr_accessible :created_at, :user_id, :priority_id, :closed, :closed_at, :user, :category, :category_id

  has_many :emails
  has_many :notes
  belongs_to :user
  belongs_to :category
  belongs_to :priority

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  scope :uncategorized, -> {where(name: 'Uncategorized')}

  has_many :cases
  has_many :emails
  has_many :key_words
  has_many :email_accounts
  belongs_to :filter

end

app/models/email.rb
require 'mail'

class Email < ActiveRecord::Base
  scope :sent, -> {where(is_sent: true)}
  scope :received, -> {where(is_sent: false)}

  attr_accessible :from, :to, :date, :subject, :case_id, :body, :raw, :category_id, :is_sent, :case


  belongs_to :case
  belongs_to :type
  belongs_to :category

  mount_uploader :raw, ZmartUploader

  #Creates a new mail

  #validates :to, presence: true
  #validates :from, presence: true

  #Decompress the raw mail
  def get_decompressed_mail
  	@mail ||= Mail.new(ActiveSupport::Gzip.decompress(get_raw))
  end



  #Get the path for the raw mail
  def get_raw
  	 @data ||= File.read raw_path
  end

  def raw_path
    @tmp_path ||= self.raw.tap { |u| u.cache_stored_file! }.path
  end
end

app/models/email_account.rb
class EmailAccount < ActiveRecord::Base
   attr_accessible :imap, :port, :enable_ssl, :user_name, :password, :email_address, :category_id

   belongs_to :category
end

app/models/filter.rb
class Filter < ActiveRecord::Base
  attr_accessible :categories, :name
  has_many :categories
end

app/models/key_word.rb
class KeyWord < ActiveRecord::Base
  attr_accessible :point, :word, :category_id
  belongs_to :category
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :body, :subject, :case_id

  belongs_to :case
  belongs_to :user
end

app/models/priority.rb
class Priority < ActiveRecord::Base
  attr_accessible :name
  has_many :cases
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  scopify
end

app/models/term.rb
class Term < ActiveRecord::Base
  attr_accessible :amount, :word

  validates_presence_of :word, :on => :create
  validates_presence_of :amount, :on => :create

end

app/models/type.rb
class Type < ActiveRecord::Base
  attr_accessible :description
  has_many :emails

end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  authenticates_with_sorcery!
  # attr_accessible :title, :body
  has_many :cases
  attr_accessible :email, :password, :password_confirmation, :first_name, :last_name

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def name
    first_name.capitalize + " " + last_name.capitalize
  end

end

app/controllers/email_accounts_controller.rb
class EmailAccountsController < ApplicationController
  def index
  	@email_accounts = EmailAccount.all
  end

  def edit
  	@email_account = EmailAccount.find(params[:id])
  end

  def new
  	@email_account = EmailAccount.new
  	@categories = Category.all
  end

  def create
  	@email_account = EmailAccount.new(params[:email_account])
    @email_account.save

    redirect_to email_accounts_path

  end

  def update
  	@email_account = EmailAccount.find(params[:id])
    @email_account.update_attributes(params[:email_account])

    if @email_account.save
      redirect_to(:back)
    else
      render action: 'edit'
    end
  end

  def destroy
  	@email_account = EmailAccount.find(params[:id])
    @email_account.destroy
    #redirect_to root_path
    redirect_to(:back)
  end

end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/email_accounts_helper.rb
module EmailAccountsHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/priorities_helper.rb
module PrioritiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wordcount_helper.rb
module WordcountHelper
end

app/views/email_accounts/_form.html.erb
<%= form_for @email_account, html: {class: "form-group"} do |f| %>
  <%= f.label :imap %>
  <%= f.text_field :imap,class: "form-control", placeholder: "Imap"%>
  <br>
  <%= f.label :port %>
  <%= f.text_field :port,class: "form-control", placeholder: "Port"%>
  <br>
  <%= f.label :enable_ssl %>
  <%= f.text_field :enable_ssl,class: "form-control", placeholder: "enable_ssl"%>
  <%= f.label :user_name %>
  <%= f.text_field :user_name,class: "form-control", placeholder: "User_name"%>
  <br>
  <%= f.label :password %>
  <%= f.text_field :password,class: "form-control", placeholder: "Password"%>
  <br>
    <%= f.label :email_address %>
  <%= f.text_field :email_address,class: "form-control", placeholder: "Email_address"%>
  <br>
  <br>
    <%= f.label :category %>
    <%= select_tag 'email_account[category_id]', 
    options_from_collection_for_select(@categories,  'id', 'name'), 
      class: "form-control", include_blank: true %>
  <br>
  <% if current_page?('categories/new') %>
    <%= f.submit "Create", class: "btn btn-primary"%>
  <%else %>
    <%= f.submit "Create", class: "btn btn-primary"%>
  <% end %>
<% end %>

app/views/email_accounts/edit.html.erb
<h1>Edit Email Account</h1>
<%= render 'form' %>

app/views/email_accounts/index.html.erb
<div class="col-sm-5">
	<h1>Email Accounts</h1>
  <table class="table table-striped">
  	<tr>
	  	<th>
	      Attached to:
	    </td>
	    <th>
	      Email Address:
	    </td>
	    <th>
	      Port:
	    </td>
			<th>
	    	SSL:
	    </td>
			<th>
	      Imap:
	    </td>
			<th>
	      Password:
	    </td>
    </tr>
    <% @email_accounts.each do |account| %>
    <tr>
    	<td>
        <%= account.category_id%>
      </td>
      <td>
        <%= account.email_address%>
      </td>
      <td>
        <%= account.port%>
      </td>
      <td>
        <%= account.enable_ssl%>
      </td>
      <td>
        <%= account.imap%>
      </td>
      <td>
        <%= account.password%>
      </td>
      <td>
        <%= link_to "edit", edit_email_account_path(account), class: "btn btn-xs btn-primary" %>
      </td>
      <td>
        <%= link_to "delete", email_account_path(account), :method => "delete", 
          :confirm => "Are you sure?", class: "btn btn-xs btn-danger" %>
      </td>      
    </tr>
    <% end %>
  </table>
	<%= link_to "New email account", email_accounts_new_path, class: "btn btn-primary" %>
</div>

app/views/email_accounts/new.html.erb
<h1>New Email Account</h1>
<%= render 'form' %>