config/routes.rb
Zmartcase::Application.routes.draw do

  get "email_accounts/index"

  get "email_accounts/edit"

  get "email_accounts/new"

  get "email_accounts/index"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  get "filter_mail/index"
  post "filter_mail/index"
  get "filter_mail/start_filtering"
  post "filter_mail/start_filtering"

  get "categories/uncategorized"
  post "categories/uncategorized"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  get "users/fetch"
  post "users/fetch"

  get "closed/:id" => "cases#closed_show", :as => "show_closed"

  resources :priorities
  resources :users
  get "dashboard" => "users#dashboard"
  resources :sessions
  resources :emails
  resources :email_accounts
  resources:notes
  resources :key_words
  resources :categories do
    resources :cases
  end

  root :to => 'users#dashboard'

end

app/models/case.rb
class Case < ActiveRecord::Base
  attr_accessible :created_at, :user_id, :priority_id, :closed, :closed_at, :user, :category, :category_id

  has_many :emails
  has_many :notes
  belongs_to :user
  belongs_to :category
  belongs_to :priority

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  scope :uncategorized, -> {where(name: 'Uncategorized')}

  has_many :cases
  has_many :emails
  has_many :key_words
  has_many :email_accounts
  belongs_to :filter

end

app/models/email.rb
require 'mail'

class Email < ActiveRecord::Base
  scope :sent, -> {where(is_sent: true)}
  scope :received, -> {where(is_sent: false)}

  attr_accessible :from, :to, :date, :subject, :case_id, :body, :raw, :category_id, :is_sent, :case


  belongs_to :case
  belongs_to :type
  belongs_to :category

  mount_uploader :raw, ZmartUploader

  #Creates a new mail

  #validates :to, presence: true
  #validates :from, presence: true

  #Decompress the raw mail
  def get_decompressed_mail
  	@mail ||= Mail.new(ActiveSupport::Gzip.decompress(get_raw))
  end



  #Get the path for the raw mail
  def get_raw
  	 @data ||= File.read raw_path
  end

  def raw_path
    @tmp_path ||= self.raw.tap { |u| u.cache_stored_file! }.path
  end
end

app/models/email_account.rb
class EmailAccount < ActiveRecord::Base
   attr_accessible :imap, :port, :enable_ssl, :user_name, :password, :email_address, :category_id

   belongs_to :category
end

app/models/filter.rb
class Filter < ActiveRecord::Base
  attr_accessible :categories, :name
  has_many :categories
end

app/models/key_word.rb
class KeyWord < ActiveRecord::Base
  attr_accessible :point, :word, :category_id
  belongs_to :category
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :body, :subject, :case_id

  belongs_to :case
  belongs_to :user
end

app/models/priority.rb
class Priority < ActiveRecord::Base
  attr_accessible :name
  has_many :cases
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  scopify
end

app/models/term.rb
class Term < ActiveRecord::Base
  attr_accessible :amount, :word

  validates_presence_of :word, :on => :create
  validates_presence_of :amount, :on => :create

end

app/models/type.rb
class Type < ActiveRecord::Base
  attr_accessible :description
  has_many :emails

end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  authenticates_with_sorcery!
  # attr_accessible :title, :body
  has_many :cases
  attr_accessible :email, :password, :password_confirmation, :first_name, :last_name

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def name
    first_name.capitalize + " " + last_name.capitalize
  end

end

app/controllers/priorities_controller.rb
class PrioritiesController < ApplicationController
  def index
    @prios = Priority.all
  end

  def show
  end

  def edit
    @prio = Priority.find(params[:id])
  end

  def update
    @prio = Priority.find(params[:id])
    @prio.update_attributes(params[:priority])

    if @prio.save
      redirect_to priorities_path, notice:  'Prio updated'
    else
      render action: 'edit'
    end
  end

  def new
    @prio = Priority.new
  end

  def create
    @prio = Priority.new(params[:priority])

    if @prio.save
      redirect_to priorities_path, notice: "Priority Created"
    else
      redirect_to priorities_path, alert: "Priority not created"
    end
  end

  def destroy
    @prio = Priority.find(params[:id])
    @prio.destroy
    redirect_to priorities_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/priorities_helper.rb
module PrioritiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wordcount_helper.rb
module WordcountHelper
end

app/views/priorities/_form.html.erb
<%= form_for @prio, html: {class: "form-group"} do |f| %>

  <%= f.label :name %>:
  <%= f.text_field :name,class: "form-control", placeholder: "Name" %><br />

  <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/priorities/edit.html.erb
<div class="col-sm-5">
  <legend><h1>Edit priority</h1></legend>
    <%= render 'form' %>
    <%= link_to "Back", priorities_path %>
</div>

app/views/priorities/index.html.erb
<div class="col-sm-5">
  <h1>Priorities</h1>
  <table class="table table-striped">
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Created at</th>
      <th></th>
      <th></th>
    </tr>
    <% @prios.each do |prio| %>
      <tr>
        <td><%= prio.id %></td>
        <td><%= prio.name %></td>
        <td><%= prio.created_at %></td>
        <td><%= link_to "edit", edit_priority_path(prio), class: "btn btn-xs btn-primary"%></td>
        <td><%= link_to "delete", priority_path(prio), :method => "delete", :confirm => "Are you sure?", class: "btn btn-xs btn-danger"%></td>
      </tr>
    <% end %>
  </table>

  <%= link_to "New priority", new_priority_path, class: "btn btn-primary" %>
</div>

app/views/priorities/new.html.erb
<div class="col-sm-5">
  <legend><h1>New Priority</h1></legend>
    <%= render 'form' %>
    <%= link_to "Back", priorities_path %>
</div>

app/views/priorities/show.html.erb
<h1>Priorities#show</h1>
<p>Find me in app/views/priorities/show.html.erb</p>