config/routes.rb
Zmartcase::Application.routes.draw do

  get "email_accounts/index"

  get "email_accounts/edit"

  get "email_accounts/new"

  get "email_accounts/index"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  get "filter_mail/index"
  post "filter_mail/index"
  get "filter_mail/start_filtering"
  post "filter_mail/start_filtering"

  get "categories/uncategorized"
  post "categories/uncategorized"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  get "users/fetch"
  post "users/fetch"

  get "closed/:id" => "cases#closed_show", :as => "show_closed"

  resources :priorities
  resources :users
  get "dashboard" => "users#dashboard"
  resources :sessions
  resources :emails
  resources :email_accounts
  resources:notes
  resources :key_words
  resources :categories do
    resources :cases
  end

  root :to => 'users#dashboard'

end

app/models/case.rb
class Case < ActiveRecord::Base
  attr_accessible :created_at, :user_id, :priority_id, :closed, :closed_at, :user, :category, :category_id

  has_many :emails
  has_many :notes
  belongs_to :user
  belongs_to :category
  belongs_to :priority

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  scope :uncategorized, -> {where(name: 'Uncategorized')}

  has_many :cases
  has_many :emails
  has_many :key_words
  has_many :email_accounts
  belongs_to :filter

end

app/models/email.rb
require 'mail'

class Email < ActiveRecord::Base
  scope :sent, -> {where(is_sent: true)}
  scope :received, -> {where(is_sent: false)}

  attr_accessible :from, :to, :date, :subject, :case_id, :body, :raw, :category_id, :is_sent, :case


  belongs_to :case
  belongs_to :type
  belongs_to :category

  mount_uploader :raw, ZmartUploader

  #Creates a new mail

  #validates :to, presence: true
  #validates :from, presence: true

  #Decompress the raw mail
  def get_decompressed_mail
  	@mail ||= Mail.new(ActiveSupport::Gzip.decompress(get_raw))
  end



  #Get the path for the raw mail
  def get_raw
  	 @data ||= File.read raw_path
  end

  def raw_path
    @tmp_path ||= self.raw.tap { |u| u.cache_stored_file! }.path
  end
end

app/models/email_account.rb
class EmailAccount < ActiveRecord::Base
   attr_accessible :imap, :port, :enable_ssl, :user_name, :password, :email_address, :category_id

   belongs_to :category
end

app/models/filter.rb
class Filter < ActiveRecord::Base
  attr_accessible :categories, :name
  has_many :categories
end

app/models/key_word.rb
class KeyWord < ActiveRecord::Base
  attr_accessible :point, :word, :category_id
  belongs_to :category
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :body, :subject, :case_id

  belongs_to :case
  belongs_to :user
end

app/models/priority.rb
class Priority < ActiveRecord::Base
  attr_accessible :name
  has_many :cases
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  scopify
end

app/models/term.rb
class Term < ActiveRecord::Base
  attr_accessible :amount, :word

  validates_presence_of :word, :on => :create
  validates_presence_of :amount, :on => :create

end

app/models/type.rb
class Type < ActiveRecord::Base
  attr_accessible :description
  has_many :emails

end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  authenticates_with_sorcery!
  # attr_accessible :title, :body
  has_many :cases
  attr_accessible :email, :password, :password_confirmation, :first_name, :last_name

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def name
    first_name.capitalize + " " + last_name.capitalize
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @cases = @category.cases
  end

  def edit
    @category = Category.find(params[:id])
    @uncategorized = Email.where(:category_id => nil)

  end

  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  def uncategorized
    @uncategorized = Email.where(:category_id => nil)
  end

  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @category = Category.find(params[:id])
    @category.update_attributes(params[:category])

    if @category.save
      #redirect_to categories_path, notice:  'Name updated'
      redirect_to(:back)
    else
      render action: 'edit'
    end
  end

  def destroy
    #TODO
    #What happens with cases?
    #delete all associated key words
    @category = Category.find(params[:id])
    @category.destroy
    #redirect_to root_path
    redirect_to(:back)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/priorities_helper.rb
module PrioritiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wordcount_helper.rb
module WordcountHelper
end

app/views/categories/_category_email.html.erb
IM HERE !

app/views/categories/_form.html.erb
<%= form_for @category, html: {class: "form-group"} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name,class: "form-control", placeholder: "Name"%>
  <br>
  <% if current_page?('categories/new') %>
  	<%= f.submit "Create", class: "btn btn-primary"%>
  <%else %>
  	<%= f.submit "Create", class: "btn btn-primary"%>
  <% end %>
<% end %>

app/views/categories/delete.html.erb
<h1>Categories#delete</h1>
<p>Find me in app/views/categories/delete.html.erb</p>

app/views/categories/edit.html.erb
<div class="col-sm-5">
  <h2>Edit Category:</h2><h1> <%= @category.name %></h1>
  <BR>
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
    Rename Category
  </button>

  <!-- Edit Project Name -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
        <div class="modal-body">
          <BR>
          	<%= render 'form' %>
          <BR>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        </div>
      </div>
    </div>
  </div>
<BR>
  <BR>
  <div class="col-sm-5">
    <h3>Attached key words:</h3>
    <table class="table table-striped">
    	<tr>
          <th>
          	Word: 
          </td>
          <th>
          	Point: 
          </td>
          <th>
            &nbsp;
          </td>
          <th>
            &nbsp;
          </td>
      </tr>
      <% @category.key_words.each do |key| %>
      <tr>
          <td>
            <%= key.word %>
          </td>
          <td>
            <%= key.point %>
          </td>
          <td>
            <td>
              <%= link_to "edit", edit_key_word_path(key), class: "btn btn-xs btn-primary" %>
            <td>
            	<%= link_to "delete", key_word_path(key), :method => "delete",
                 :confirm => "Are you sure?", class: "btn btn-xs btn-danger" %>
          	</td>
        </tr>
        <% end %>
    </table>
    <BR>
    <%= link_to "Add key word", new_key_word_path , class: "btn btn-primary btn-sm" %>
    <BR>
      <BR>
    <%= button_to "Filter all emails", filter_mail_start_filtering_path, class: "btn btn-primary" %>
    <BR>
    <h3></h3>
    <table class="table table-striped">
    	<tr>
        <th>
          Emails without a category:
        </td>
        </tr>
        <% @uncategorized.each do |email| %>
        <tr>
          <td>
            <%= email.subject%>
          </td>
        </tr>
        <% end %>
    </table>

</div>

app/views/categories/index.html.erb
<div class="col-sm-5">
  <h1>Categories</h1>
  <table class="table table-striped">
    <tr>
      <th>#</td>
      <th>Name</td>
      <th>Created at</td>
        <th> </td>
    </tr>
    <% @categories.each do |cat| %>
      <tr>
        <td><%= cat.id %></td>
        <td><%= cat.name %></td>
        <td><%= cat.created_at %></td>
        <td>
          <%= link_to "edit", edit_category_path(cat), class: "btn btn-xs btn-primary" %>
        </td>
        <td>
          <%= link_to "delete", category_path(cat), :method => "delete", 
            :confirm => "Are you sure?", class: "btn btn-xs btn-danger" %>
        </td>
      </tr>
    <% end %>
  </table>

  <%= link_to "New category", new_category_path, class: "btn btn-primary" %>
</div>

app/views/categories/new.html.erb
<div class="col-sm-5">
  <legend><h1>New Category</h1></legend>
  <%= render 'form' %>
</div>

app/views/categories/show.html.erb
<div class="pure-g">
    <div id="mail-list" class="pure-u-1-3">
      <ul>
          <% @cases.each do |case| %>
            <li id="mail-item">
              <h5 class="email-name">Tilo Mitra</h5>
              <h4 class="email-subject"><%= case.id %></h4>
              <p class="email-desc">
                <%= case.id %>
              </p>
            </li>
          <% end %>

      </ul>
    </div>
    <div class="pure-u"><h4> Select email </h4></div>
</div>

app/views/categories/uncategorized.html.erb
<BR>
    <%= link_to "Add key word", new_key_word_path , class: "btn btn-primary btn-sm" %>
    <BR>
      <BR>
    <%= button_to "Filter all emails", filter_mail_start_filtering_path, class: "btn btn-primary" %>
    <BR>
    <table class="table table-striped">
    	<tr>
            <th>
              Emails without a category:
            </td>
        </tr>
        <% @uncategorized.each do |email| %>
        <tr>
          <td>
            <%= email.subject%>
          </td>
        </tr>
        <% end %>
    </table>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>